name: point2mesh
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
#  - pytorch3d
dependencies:
  - python=3.8.2
  - numpy=1.18.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - fvcore=0.1
#  - pytorch3d=0.2.0
  - pip
  - pip:
    - pytest==5.4.2


# pip install -U torch==1.5
# torch1.4和pytorch3d=0.2.0不匹配！！！

"""
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    for part_i, est_verts in enumerate(net(rand_verts, part_mesh)):
  File "/home/dingchaofan/point2mesh/models/networks.py", line 155, in forward
    results = super().forward(relevant_edges, [p])
  File "/home/dingchaofan/point2mesh/models/networks.py", line 103, in forward
    x, _ = self.encoder_decoder(x, meshes_new)
  File "/home/dingchaofan/.conda/envs/point2mesh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dingchaofan/point2mesh/models/networks.py", line 181, in forward
    fe, before_pool = self.encoder((x, meshes))
  File "/home/dingchaofan/.conda/envs/point2mesh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dingchaofan/point2mesh/models/networks.py", line 309, in forward
    fe, before_pool = conv((fe, meshes))
  File "/home/dingchaofan/.conda/envs/point2mesh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dingchaofan/point2mesh/models/networks.py", line 222, in forward
    x2 = self.pool(x2, meshes)
  File "/home/dingchaofan/point2mesh/models/layers/mesh_pool.py", line 17, in __call__
    return self.forward(fe, meshes)
  File "/home/dingchaofan/point2mesh/models/layers/mesh_pool.py", line 25, in forward
    self.__pool_main(mesh_index)
  File "/home/dingchaofan/point2mesh/models/layers/mesh_pool.py", line 42, in __pool_main
    fe = edge_groups.rebuild_features(self.__fe[mesh_index], mask, self.__out_target)
  File "/home/dingchaofan/point2mesh/models/layers/mesh_union.py", line 29, in rebuild_features_average
    fe = torch.matmul(features.squeeze(-1), self.groups)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
"""